version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-gradle-dependencies:
        patterns: [ "*" ]
        update-types: [ "minor", "patch", "major" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns: [ "*" ]
