version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-gradle-dependencies:
        patterns: ["*"]
    allow:
      - dependency-type: "all"
      - update-types: ["semver:major", "semver:minor", "semver:patch", "semver:pre"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns: ["*"]
