[versions]
agp = "9.3.2"
kotlin = "2.4.10"
room = "2.8.4"
retrofit = "3.0.0"
moshi = "1.15.2"
compose = "1.11.4"
compose-m3 = "1.5.0-alpha23"
compose-m3-adaptive = "1.2.0"
compose-m3-window-size = "1.4.0"
compose-runtime = "2.11.0"
compose-core = "1.7.8"
accompanist = "0.37.3"
hilt = "2.60.1"
hilt-navigation = "1.4.0"
jupiter = "6.1.3"
mockk = "1.14.11"
turbine = "1.2.1"
kotlin-coroutines = "1.11.0"
kotlin-serialization = "1.11.0"
kotlin-collections-immutable = "0.5.2"
google-services = "4.5.0"
ksp = "2.3.11"
work-runtime-ktx = "2.11.2"
work-hilt = "1.4.0"
app-compat = "1.8.0"
ok-http = "5.5.0"
timber = "5.0.1"
nav3Core = "1.1.4"
play-services = "25.4.0"
firebase-bom = "34.18.0"
firebase-crashlytics-plugin = "3.0.8"
ump-consent = "4.0.0"
glance = "1.1.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-m3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-m3" }
androidx-compose-ui-m3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "compose-m3-adaptive" }
androidx-compose-m3-windowsize = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "compose-m3-window-size" }
androidx-compose-ui-m3-core = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-core" }
androidx-compose-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-runtime" }

androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

androidx-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

androidx-work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }
androidx-work-manager-hilt = { group = "androidx.hilt", name = "hilt-work", version.ref = "work-hilt" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }

retrofit-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "ok-http" }
retrofit-convertor-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-lib = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }

junit-test = { group = "junit", name = "junit", version = "4.13.2" }
jupiter-test = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }
jupiter-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
jupiter-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "jupiter" }
mockk-test = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine-test = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }

google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

kotlinMetadataJvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlin" }

androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "play-services" }
play-ump-consent = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "ump-consent" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
com-google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
org-jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-gms-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlaytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin"}

[bundles]
androidx-room = [
    "androidx-room-runtime",
    "androidx-room-ktx"
]

androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-ui-preview",
    "androidx-compose-ui-m3",
    "androidx-compose-ui-m3-adaptive",
    "androidx-compose-m3-windowsize",
    "androidx-compose-ui-m3-core",
    "androidx-compose-runtime"
]

androidx-navigation3 = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui"
]

androidx-compose-tooling = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-manifest"
]

androidx-accompainst = [
    "androidx-accompanist-permissions"
]

androidx-work-manager = [
    "androidx-work-manager",
    "androidx-work-manager-hilt"
]

retrofit = [
    "retrofit-okhttp",
    "retrofit-convertor-gson",
    "retrofit-lib",
    "retrofit-moshi-kotlin"
]

unit-test = [
    "junit-test",
    "jupiter-test",
    "jupiter-engine",
    "jupiter-params",
    "jupiter-launcher",
    "jupiter-vintage",
    "mockk-test",
    "turbine-test",
    "coroutines-test"
]

hilt = [
    "google-dagger-hilt-android",
    "androidx-hilt-navigation-compose"
]

kotlinx = [
    "kotlinx-coroutines",
    "kotlinx-serialization-json",
    "kotlinx-collections-immutable"
]

play-services = [
    "play-services-ads",
    "play-ump-consent"
]

firebase-services = [
    "firebase-analytics",
    "firebase-crashlytics"
]

glance = [
    "androidx-glance-appwidget"
]
