name: Run quality checks
on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v3

      - name: Run unit tests
        run: ./gradlew test